# Generated by Django 5.2.4 on 2025-07-12 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان کار')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('completed', models.BooleanField(default=False, verbose_name='انجام شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
            ],
            options={
                'verbose_name': 'کار',
                'verbose_name_plural': 'کارها',
                'ordering': ['completed', '-created_at'],
            },
        ),
    ]
